name: publish

on:
  # Triggered when new "Release" page is published.
  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#release
  release:
    types: [published]

env:
  # Leave these lines unchanged
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
  # GITHUB_PACKAGES_TOKEN: ${{ secrets.GITHUB_PACKAGES_TOKEN }}
  DIST_DIR: dist

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest repository
      uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    # Save and restore from caches
    - name: Cache npm cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Install dependencies
      run: npm ci

    - name: Run lint
      run: npm run lint

    - name: Run test
      run: npm test

    - name: Build and publish
      run: |
        npm config set //registry.npmjs.org/:_authToken=${{ env.NPM_REGISTRY_TOKEN }}
        npx can-npm-publish@1.3.2 && npm publish
    #     npm config set //npm.pkg.github.com/:_authToken=${{ env.GITHUB_PACKAGES_TOKEN }}
    #     npm publish

    - name: Upload built files
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ${{ env.DIST_DIR }}
